### ISSUE TITLE
关于在安卓端使用feedme 无法获取订阅内容的询问

### ISSUE THREAD

**Issue by MuXia-0326** [Colin-XKL/RSSmanX#16]
之前在买的腾讯云的服务器上搭建，是可以正常的

最近自己弄了一台服务器，然后在本地也部署了一套，并且有公网ip，但是本地部署的这一套无法在安卓的feedme上获取到内容
订阅的信息源可以获取到，但就是获取不到信息源内的内容

请问一下作者大大，这可能是哪方面有问题？

**Comment by MuXia-0326** [comment]
就是web端访问 都是正常的 可以获取订阅源里面的文章
但app同步内容的时候只能把订阅源拿到，互殴去不到里面的文章
已经在设置中开启允许api访问

**Comment by Colin-XKL** [comment]
你现在的feedme是通过什么接口连接ttrss的？如果我没记错的话，feedme应该是有个ttrss专用的入口，还有一堆其他feed reader的。连接ttrss可以通过ttrss专用入口，也可以通过fever入口走fever api跟ttrss 通信，当然后者需要在ttrss端安装并启用fever插件。

feedme通过ttrss专用入口连接ttrss后端的方式有兼容性问题，早在去年年底就有很多人反馈了，可以参考下这里 https://github.com/HenryQW/Awesome-TTRSS/issues/428

如果你是刚好遇到了这个兼容性问题，可以通过更换版本或者更换为fever方式接入来解决

**Comment by MuXia-0326** [comment]
ok，用fever api解决了，感谢
