### ISSUE TITLE
关于github官方rss源的问题

### ISSUE THREAD

**Issue by MuXia-0326** [Colin-XKL/RSSmanX#18]
`https://github.com/Colin-XKL/RSSmanX/commits.atom`
这个可以直接访问，但是导入项目的ttrss中就无法使用

clash配置有配置github的规则，让其走代理

以下是调试报错
![image](https://github.com/Colin-XKL/RSSmanX/assets/63834850/7d93e8e7-7559-412f-b01a-cf3a9a9aedc8)

> 不知是不是github更改的rss源的格式，没有留有原格式的数据

**Comment by Colin-XKL** [comment]
这个似乎是 GitHub 的一个 bug。访问任何 repo 的 release 的 atom feed一切正常，但是访问 commits 的 atom feed，返回的结果会根据请求 header 中的 accept 参数而变化，如通过浏览器访问，返回的是正常的 xml 格式，但是通过 curl 或者其他方式指定 accept 为json 的话，返回的实际是一个 json。

**Comment by MuXia-0326** [comment]
> 这个似乎是 GitHub 的一个 bug。访问任何 repo 的 release 的 atom feed一切正常，但是访问 commits 的 atom feed，返回的结果会根据请求 header 中的 accept 参数而变化，如通过浏览器访问，返回的是正常的 xml 格式，但是通过 curl 或者其他方式指定 accept 为json 的话，返回的实际是一个 json。

这可真是个悲伤的故事，有地方可以给github提供反馈，让其修bug吗？

**Comment by Colin-XKL** [comment]
我再 Github community 开了一个 discussion 报告了这个 bug，可以关注下  https://github.com/orgs/community/discussions/86096

**Comment by MuXia-0326** [comment]
> 我在 Github community 开了一个 discussion 报告了这个 bug，可以关注下 https://github.com/orgs/community/discussions/86096

好的，感谢作者
