### ISSUE TITLE
为什么rsshub无法通过浏览器打开？

### ISSUE THREAD

**Issue by geerda123** [Colin-XKL/RSSmanX#2]
![image](https://user-images.githubusercontent.com/18500636/126891929-de607c8a-ebee-4cb1-8838-9585f6e77f0b.png)
为什么注销1200端口？我无论取消注销和保留原始代码都无法通过浏览器打开rsshub

**Comment by Colin-XKL** [comment]
因为我把它改成80端口访问了哈哈

**Comment by Colin-XKL** [comment]
你圈出来的地方是一个历史遗留问题，RSSHub默认是开放1200端口，访问需要通过1200端口，订阅自建的rsshub也需要通过1200端口。TTRSS之前有一个很大的变更，只允许订阅80和443端口。当时那一波升级导致很多人ttrss订阅的自建rsshub的feed突然都用不了。有两个解决方案，一个是修改ttrss的设置，另一个就是修改自建rsshub的端口，我这里采取的后者，下面environment那里我把rsshub的默认端口改成80了

**Comment by geerda123** [comment]
@Colin-XKL 所以怎么进入RSSHUB http://ip 根本无法进入rsshub界面，只修改了SELF_URL_PATH

**Comment by Colin-XKL** [comment]
你是本机部署的还是在云服务器上部署的？

如果是云服务器上部署的，你需要修改端口映射。为了防止自建的rsshub被滥用，默认情况下是不开放公网访问的。把port那两行取消注释，改成80：80映射就可以了。

SELF_URL_PATH只影响ttrss的访问，不会影响到rsshub

**Comment by geerda123** [comment]
谢谢，成功解决了。这个项目应该多多宣传
