### ISSUE TITLE
你好，碰见个新问题，为什么选择ultimate版本自建后wemp仍然被屏蔽？

### ISSUE THREAD

**Issue by geerda123** [Colin-XKL/RSSmanX#3]
你好，我刚才试过了，美国vps，该ip代理直接浏览wemp没有被屏蔽，但是用ultimate版的rsshub第一次可以获取rss内容，以后就被屏蔽了。请问你是怎么处理微信公众号rss获取的？谢谢
![image](https://user-images.githubusercontent.com/18500636/126893681-562148e8-1b47-4f22-b639-be40d7c4115c.png)

**Comment by Colin-XKL** [comment]
目前来说，应对反爬严格的站点主要有两种策略：**换用不同的节点去请求目标站点**，或者**尽可能模拟真实用户的访问**。目前版本的RSS Man使用的是前者。

对于wemp这类反爬严格的站点，目前的处理方案是，每次请求的时候都会随机选取一个代理节点，每次都是不一样的节点不容易被封，有时候会选到质量较差或者已经被封的节点，多重试几次就会有可用的节点啦。连接的质量不是很稳定，不过一般来说ttrss会自动帮你完成失败重试，你使用rss的时候基本是无感的。

你是自己在调试的话，多重试几次就好啦

**Comment by Colin-XKL** [comment]
这个项目之前都是我自己在使用，很多场景我并没有进行充分测试，文档也没写😂。有任何问题欢迎issue提问交流

**Comment by geerda123** [comment]
谢谢啊，解决了。就是第三方有的公众号更新慢或者断更了，以后还要找找新的方法
